name: Pylint

on: [push]

jobs:
 my_first_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd 
          ls -alF

 my_second_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get update 
          sudo apt-get install tree 
          tree -F .       
            
 my_third_job:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .
    
 black:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install black
          black --check .
        
 pytest:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install matplotlib requests IPython pytest
          pytest .
